### ISSUE TITLE
Handle Timeline containers

### ISSUE THREAD

**Issue by peter88213** [peter88213/yw-timeline#3]
At the beginning of the XML event "text" entry there may be a link to a container in round brackets. This must be taken into account, i.e. it should neither appear in the yWriter scene description nor be overwritten during synchronization.

**Comment by peter88213** [comment]
First idea: 
Upon synchronization with yWriter, convert the bracketed numbers into UIDs looking like"ContID:1" and store them as item tags.

**Comment by kauffy** [comment]
My thought for these (waving a magic wand, of course), is that it could be user-dependent how they wanted the containers handled. My first thought is that containers could make great Chapters-- after all, they contain Events (Scenes), but also recognizing that someone else may have a different use in mind for them, like (as you say), having a certain Container result in a specific tag on the Scene), or even the viewpoint character-- that could be useful for someone who really gets into the character and wants to do their writing at a stretch.
I realize the headache it could create. You'd need some type of "pair file" to know how the sync is setup, and also-- messy!

**Comment by peter88213** [comment]
As far as I found out, the containers in Timeline are used to create groups of events with a fixed time reference. If you move a container, the time intervals of the members are preserved. This concept has no counterpart in yWriter, and I would not misuse it. 
My issue was really just about making the container information invisible in yWriter so that it wouldn't be touched accidentally. I can also remove it altogether and restore it from the timeline project during synchronization.

**Comment by peter88213** [comment]
The other way round, yWriter scene titles beginning with a bracketed word will cause unreadable timelines, since Timeline's XML parser takes it as an invalid container ID and throws an exception. So for now, be sure not to begin scene titles with brackets.

**Comment by peter88213** [comment]
With v0.8.0, this is implemented:

- Containers are invisible in yWriter.
- Synchronization does not affect the membership of an event in a container. 
- Scene titles beginning with an opening bracket '(' or '[') are automatically prefixed with '_' in Timeline. Do not remove this prefix; it will not appear in yWriter after synchronization.
